name: C/C++ Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy cppcheck
      # - name: run clang-tidy
      #   run: |
      #     find . -type f \( -name "*.cpp" -or -name "*.hpp" \) | xargs clang-tidy -p build
      - name: run cppcheck
        run: |
          cppcheck --enable=all --error-exitcode=1 .
